# Generated by Django 5.2.3 on 2025-06-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do produto', null=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, help_text='Preço de venda', max_digits=10)),
                ('quantidade', models.PositiveIntegerField(default=0, help_text='Quantidade em estoque')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
