# Generated by Django 5.2.3 on 2025-06-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentoestoque',
            options={'ordering': ['-data_movimentacao']},
        ),
        migrations.RenameField(
            model_name='movimentoestoque',
            old_name='timestamp',
            new_name='data_movimentacao',
        ),
    ]
