# Generated by Django 5.2.3 on 2025-06-12 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Preço de compra', max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
