# Generated by Django 5.2.3 on 2025-07-10 23:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movimentoestoque_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_compra',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='usuario',
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Estoque'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Custo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Venda'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Cadastro')),
                ('cliente_de_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome', 'sobrenome'],
            },
        ),
        migrations.CreateModel(
            name='ItemCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('tipo_movimentacao', models.IntegerField(choices=[(1, 'Entrada'), (2, 'Saída')], verbose_name='Tipo de Movimentação')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('data_movimentacao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data da Movimentação')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.IntegerField(choices=[(1, 'Em Andamento'), (2, 'Aguardando Peça'), (3, 'Concluído'), (4, 'Cancelado')], default=1, verbose_name='Situação')),
                ('data_inicio', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Início')),
                ('data_termino', models.DateTimeField(blank=True, null=True, verbose_name='Data de Término')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_de_servico', to='core.cliente', verbose_name='Cliente')),
                ('item_do_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemcliente')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pagamento')),
                ('data_pagamento', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data do Pagamento')),
                ('ordem_de_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.ordemdeservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_em_os', to='core.movimentacao', verbose_name='Produto em Movimentação')),
                ('ordem_de_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_os', to='core.ordemdeservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Produto na OS',
                'verbose_name_plural': 'Produtos na OS',
            },
        ),
        migrations.DeleteModel(
            name='MovimentoEstoque',
        ),
    ]
