# Generated by Django 5.2.3 on 2025-06-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_preco_compra_alter_produto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Preço de compra', max_digits=10),
        ),
    ]
