version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: meuestoqueteste
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  postgres_data: